<?php
namespace vbac;

use itdq\DbTable;


/*
 * CREATE TABLE ROB_DEV.PERSON_SUBPLATFORM ( CNUM CHAR(9) NOT NULL, SUBPLATFORM CHAR(50) NOT NULL ) IN USERSPACE1;
 * ALTER TABLE ROB_DEV.PERSON_SUBPLATFORM ADD CONSTRAINT SSP_PK PRIMARY KEY (CNUM,SUBPLATFORM ) NOT ENFORCED;
 *
 */

class PersonSubPlatformTable extends DbTable
{

}

