<?php

use PhpOffice\PhpSpreadsheet\Helper\Sample;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use itdq\DbTable;
use itdq\BlueMail;
use vbac\personTable;

set_time_limit(0);
ini_set('memory_limit','2048M');

$_ENV['email'] = 'on';

// require_once __DIR__ . '/../../src/Bootstrap.php';
// $helper = new Sample();
// if ($helper->isCli()) {
//     $helper->log('This example should only be run from a Web Browser' . PHP_EOL);
//     return;
// }

$noreplemailid = $_ENV['noreplykyndrylemailid'];
$emailAddress = array(
    // 'philip.bibby@kyndryl.com',
    $_ENV['automationemailid']
);

// Create new Spreadsheet object
$spreadsheet = new Spreadsheet();
// Set document properties
$spreadsheet->getProperties()->setCreator('vBAC')
    ->setLastModifiedBy('vBAC')
    ->setTitle('Headcount Report')
    ->setSubject('Headcount Report')
    ->setDescription('Headcount Report generated by vBAC')
    ->setKeywords('office 2007 openxml php vbac Headcount Report')
    ->setCategory('Headcount Report');
    // Add some data

$now = new DateTime();
$withProvClear = null;

try {
    
    // ob_clean();

    $sql = " SELECT ";
    $sql.=" P.KYN_EMAIL_ADDRESS AS Email_Address,";
    $sql.=" P.CNUM AS CNUM,";
    $sql.=" P.WORKER_ID AS Peronsal_ID_SAP,";
    $sql.=" P.FIRST_NAME AS First_Name,";
    $sql.=" P.LAST_NAME AS Last_Name,";

    // $sql.=personTable::FULLNAME_SELECT.",";
    $str1 = personTable::FULLNAME_SELECT.",";
    $search = array('AS FULL_NAME');
    $replace = array('AS full_name');
    $sql.=str_replace($search, $replace, $str1);
    
    // $sql.=personTable::EMPLOYEE_TYPE_SELECT.",";
    $str2 = personTable::EMPLOYEE_TYPE_SELECT.",";
    $search = array('AS EMPLOYEE_TYPE_CODE', 'AS EMPLOYEE_TYPE');
    $replace = array('AS employee_type_code', 'AS employee_type');
    $sql.=str_replace($search, $replace, $str2);

    $sql.=" P.BUSINESS_TITLE AS Job_Title,";
    $sql.=" 'tbc' AS Band,";
    $sql.=" P.COUNTRY AS Country,";
    $sql.=" P.LBG_LOCATION AS LBG_Approved_Location,";
    $sql.=" SS.SKILLSET AS Skillset,";
    $sql.=" P.START_DATE AS Start_Date,";
    $sql.=" P.PROJECTED_END_DATE AS Projected_End_Date,";
    $sql.=" P.PES_STATUS AS PES_Status,";
    $sql.=" P.PES_CLEARED_DATE AS PES_Cleared_Date,";
    $sql.=" P.PES_RECHECK_DATE AS PES_Recheck_Date,";
    $sql.=" P.PES_LEVEL AS PES_Level,";
    $sql.=" AS1.SQUAD_NAME AS Squad_Name,";
    $sql.=" AS1.SQUAD_LEADER AS Squad_Leader,";
    $sql.=" AS1.ORGANISATION AS Squad_Organisation,";
    $sql.=" AT.TRIBE_NAME AS Tribe_Name,";
    $sql.=" AT.TRIBE_LEADER AS Tribe_Leader,";
    $sql.=" AT.ORGANISATION AS Tribe_Organisation,";
    $sql.=" F.KYN_EMAIL_ADDRESS AS Functional_Manager,";
    $sql.=" P.MATRIX_MANAGER_EMAIL AS Workday_Manager,";
    $sql.=" P.CT_ID AS CT_ID,";
    $sql.=" P.LBG_EMAIL AS LBG_Email_Address";

    // $sql.=personTable::ORGANISATION_SELECT.", ";
    // $sql.=personTable::FLM_SELECT.", ";
    // $sql.=personTable::SLM_SELECT.", ";
    
    // $sql.= personTable::getStatusSelect($withProvClear, 'P');
    $sql.= personTable::getTablesForQuery();
    $sql.= " WHERE 1=1 AND trim(P.KYN_EMAIL_ADDRESS) != '' ";
    $sql.= " ORDER BY P.KYN_EMAIL_ADDRESS ";

    $resultSet = sqlsrv_query($GLOBALS['conn'], $sql);

    if ($resultSet) {
        DbTable::writeResultSetToXls($resultSet, $spreadsheet);
    }
    
    DbTable::autoFilter($spreadsheet);
    DbTable::autoSizeColumns($spreadsheet);
    DbTable::setRowColor($spreadsheet,'19DDEBF7',1);
    
    $spreadsheet->setActiveSheetIndex(0);
    $spreadsheet->getActiveSheet()->setTitle('Headcount Report');
    
    // Set active sheet index to the first sheet, so Excel opens this as the first sheet
    $spreadsheet->setActiveSheetIndex(0);
    // Redirect output to a client�s web browser (Xlsx)
    DbTable::autoSizeColumns($spreadsheet);
    // $filePrefix = 'Headcount Report - ';
    $fileNameSuffix = $now->format('Ymd_His');
    // $fileNamePart = $filePrefix . $fileNameSuffix . '.xlsx';
    $fileNamePart = 'Headcount Report.xlsx';
    $scriptsDirectory = '/var/www/html/extracts/';
    $fileName = $scriptsDirectory.$fileNamePart;  

    $writer = IOFactory::createWriter($spreadsheet, 'Xlsx');
    // $writer->save('php://output');
    $writer->save($fileName);

    $attachments = array();
    $handle = fopen($fileName, "r", true);
    if ($handle !== false) {
        $applicationForm = fread($handle, filesize($fileName));
        fclose($handle);
        $encodedAttachmentFile = base64_encode($applicationForm);
        $attachments[] = array(
            'filename'=>$fileNamePart,
            'content_type'=>'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'data'=>$encodedAttachmentFile,
            'path'=>$fileName
        );
    }
    
    $result = BlueMail::send_mail($emailAddress, 'Draft version of Headcount Report : ' . $fileNameSuffix, 'Please find attached Headcount Report XLS',$noreplemailid,array(),array(),true,$attachments);    
    var_dump($result);

} catch (Exception $e) {
    
    //    ob_clean();
    
    echo "<br/><br/><br/><br/><br/>";
    
    echo $e->getMessage();
    echo $e->getLine();
    echo $e->getFile();
    echo "<h1>No data found to export to tracker</h1>";
}