apiVersion: apps/v1
kind: Deployment
metadata:
  name: vbac
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: 0 # Default to 10 if not specified
  selector:
    matchLabels:
      app: vbac
  template:
    metadata:
      labels:
        app: vbac
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      securityContext: {}
      automountServiceAccountToken: false
      dnsPolicy: ClusterFirst
      containers:
      - name: vbac
        image: {{ .Values.image.repository | trim }}:{{ .Values.image.tag | trim }}
        resources:
          limits:
            # no cpu limit! this is excluded on purpose
            # cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
        terminationMessagePath: /dev/termination-log
        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        terminationMessagePolicy: File
        env:
        - name: PORT
          value: '{{ .Values.service.port }}'
        - name: TEMP_INLINE_VALUE
          # we can also pass env variables like in this way 
          value: Linux
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: vbac-app-docker-secrets
        - secretRef:
            name: vbac-app-docker-secrets-cfirst
        - secretRef:
            name: vbac-app-docker-secrets-db
        - secretRef:
            name: vbac-app-docker-secrets-redis
        - secretRef:
            name: vbac-app-docker-secrets-smtp
        - secretRef:
            name: vbac-app-docker-secrets-sso
        - secretRef:
            name: vbac-app-docker-secrets-worker-api
