	
ALTER TABLE vbac_ut.person
 ADD COLUMN sys_start TIMESTAMP(12) NOT NULL GENERATED AS ROW BEGIN IMPLICITLY HIDDEN
 ADD COLUMN sys_end   TIMESTAMP(12) NOT NULL GENERATED AS ROW END IMPLICITLY HIDDEN
 ADD COLUMN trans_id  TIMESTAMP(12) GENERATED AS TRANSACTION START ID IMPLICITLY HIDDEN
 ADD PERIOD SYSTEM_TIME (sys_start, sys_end);
                 
CREATE TABLE vbac_ut.person_history LIKE vbac_ut.person;
                 
ALTER TABLE vbac_ut.person ADD VERSIONING USE HISTORY TABLE vbac_ut.person_history;





alter table ROB_DEV.ASSET_REQUESTS DROP VERSIONING;

alter table ROB_DEV.ASSET_REQUESTS_HISTORY DROP COLUMN ORDERIT_RESPONDED;

alter table ROB_DEV.ASSET_REQUESTS ADD VERSIONING USE HISTORY TABLE ROB_DEV.ASSET_REQUESTS_HISTORY;

alter table ROB_DEV.ASSET_REQUESTS_HISTORY add column ORDERIT_RESPONDED DATE;
