ALTER TABLE "ROB_DEV"."AGILE_TRIBE" ADD COLUMN "ORGANISATION" CHAR(25) NOT NULL WITH DEFAULT 'Managed Services';
ALTER TABLE "VBAC_UT"."AGILE_TRIBE" ADD COLUMN "ORGANISATION" CHAR(25) NOT NULL WITH DEFAULT 'Managed Services';

CALL SYSPROC.ADMIN_CMD( 'REORG TABLE ROB_DEV.AGILE_TRIBE' );
