DROP TABLE "ROB_DEV"."DLP";

CREATE TABLE "ROB_DEV"."DLP" (
		"CNUM" char(9) not null,
		"APPROVER_EMAIL" CHAR(40) ,
		"APPROVED_DATE" DATE,
		"HOSTNAME" CHAR(15) not null,
		"CREATION_DATE" DATE not null default CURRENT DATE,
		"TRANSFERRED_TO_HOSTNAME" CHAR(15),
		"TRANSFERRED_DATE" DATE,
		"TRANSFERRED_EMAIL" CHAR(40),
		"EXCEPTION_CODE" CHAR(5) not null default '266',
		"STATUS" CHAR(20) not null default 'pending'
	)
	DATA CAPTURE NONE;
	

ALTER TABLE "ROB_DEV"."DLP" ADD CONSTRAINT "DLPPrimary" PRIMARY KEY
	("HOSTNAME","CREATION_DATE");
	
	