CREATE TABLE "VBAC"."STATIC_GROUPS_FOR_ROLES" (
		"GROUP_ID" INTEGER NOT NULL,
		"ROLE_ID" INTEGER NOT NULL
	)
	DATA CAPTURE NONE;

ALTER TABLE "VBAC"."STATIC_GROUPS_FOR_ROLES" ADD CONSTRAINT "Q_GROUP_GROU00002_00001" PRIMARY KEY
	("GROUP_ID","ROLE_ID");

