DROP TABLE "ROB_DEV"."PERSON";

CREATE TABLE "ROB_DEV"."PERSON" (
		"CNUM" char(9) not null,
		"OPEN_SEAT_NUMBER" CHAR(12) ,
		"FIRST_NAME" CHAR(20),
		"LAST_NAME" CHAR(20),
		"EMAIL_ADDRESS" CHAR(40),
		"LBG_EMAIL" CHAR(40),
		"EMPLOYEE_TYPE" CHAR(20),
		"FM_CNUM" INTEGER,
		"FM_MANAGER_FLAG" CHAR(3),
		"CTB_RTB" CHAR(10),
		"TT_BAU" CHAR(3),
		"LOB" CHAR(40),
		"ROLE_ON_THE_ACCOUNT" CHAR(40),
		"ROLE_TECHNOLOGY" CHAR(40),
		"START_DATE" DATE,
		"PROJECTED_END_DATE" DATE,
		"COUNTRY" CHAR(40),
		"IBM_BASE_LOCATION" VARCHAR(512),
		"LBG_LOCATION" VARCHAR(512),
		"OFFBOARDED_DATE" DATE,
		"PES_DATE_REQUESTED" DATE,
		"PES_REQUESTOR" CHAR(40),
		"PES_DATE_RESPONDED" DATE,
		"PES_STATUS_DETAILS" VARCHAR(100),
		"PES_STATUS" CHAR(10),
		"REVALIDATION_DATE_FIELD" DATE,
		"REVALIDATION_STATUS" CHAR(10),
		"CBN_DATE_FIELD" DATE,
		"CBN_STATUS" CHAR(10),
		"WORK_STREAM" CHAR(40)
	)
	DATA CAPTURE NONE;


ALTER TABLE "ROB_DEV"."PERSON" ADD CONSTRAINT "SQL171213120532360" PRIMARY KEY
	("CNUM");

