DROP TABLE "ROB_DEV"."PERSON";

CREATE TABLE "ROB_DEV"."PERSON" (
		"CNUM" INTEGER NOT NULL,
		"OPEN_SEAT_NUMBER" INTEGER,
		"FIRST_NAME" CHAR(20),
		"LAST_NAME" CHAR(20),
		"PHONE_NUMBER" INTEGER,
		"EMAIL_ADDRESS" VARCHAR(120),
		"LBG_EMAIL" CHAR(40),
		"EMPLOYEE_TYPE" CHAR(20),
		"WORK_STREAM" CHAR(40),
		"FM_EMAIL" VARCHAR(120),
		"FM_MANAGER_FLAG" CHAR(3),
		"CTB_RTB" CHAR(10),
		"TT_BAU" CHAR(3),
		"LOB" CHAR(40),
		"ROLE_ON_THE_ACCOUNT" CHAR(40),
		"ROLE_TECHNOLOGY" CHAR(40),
		"START_DATE" DATE,
		"PROJECTED_END_DATE" DATE,
		"THIRD_PARTY_VDI_ACCESS" CHAR(3),
		"EXTERNAL_COMPANY" CHAR(40),
		"COUNTRY" CHAR(40),
		"CT_ID" INTEGER,
		"CT_REQUEST" TIMESTAMP,
		"CYBERARK" CHAR(3),
		"FM_APPROVAL" CHAR(10),
		"FULL_VPN" CHAR(3),
		"IBM_BASE_LOCATION" VARCHAR(512),
		"LBG_LOCATION" VARCHAR(512),
		"LAPTOP_ASSET" CHAR(3),
		"MPW_ACCOUNT_TYPE" CHAR(10),
		"MPW_DOMAIN" CHAR(20),
		"MPW_ID" CHAR(10),
		"OCS" CHAR(3),
		"OFFBOARDED_DATE" DATE,
		"PES_DATE_REQUESTED" TIMESTAMP,
		"PES_DATE_RESPONDED" TIMESTAMP,
		"PES_DETAILS" CHAR(3),
		"PES_STATUS" CHAR(10),
		"RAS_ACCESS" CHAR(3),
		"REVALIDATION_DATE_FIELD" TIMESTAMP,
		"REVALIDATION_STATUS" CHAR(10),
		"SDID" CHAR(3),
		"VDI" CHAR(3),
		"VPN_LITE" CHAR(3)

	)
	DATA CAPTURE NONE;

ALTER TABLE "ROB_DEV"."PERSON" ADD CONSTRAINT "SQL171213120532360" PRIMARY KEY
	("CNUM");

