--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "VBAC_UT"."PERSON" (
		"CNUM" CHAR(9) NOT NULL,
		"OPEN_SEAT_NUMBER" CHAR(12),
		"FIRST_NAME" CHAR(30),
		"LAST_NAME" CHAR(40),
		"EMAIL_ADDRESS" CHAR(60),
		"NOTES_ID" CHAR(60),
		"LBG_EMAIL" CHAR(60),
		"EMPLOYEE_TYPE" CHAR(20),
		"FM_CNUM" CHAR(9),
		"FM_MANAGER_FLAG" CHAR(3),
		"CTB_RTB" CHAR(10),
		"TT_BAU" CHAR(3),
		"LOB" CHAR(40),
		"ROLE_ON_THE_ACCOUNT" VARCHAR(120),
		"ROLE_TECHNOLOGY" CHAR(40),
		"START_DATE" DATE,
		"PROJECTED_END_DATE" DATE,
		"COUNTRY" CHAR(40),
		"IBM_BASE_LOCATION" VARCHAR(512),
		"LBG_LOCATION" VARCHAR(512),
		"OFFBOARDED_DATE" DATE,
		"PES_DATE_REQUESTED" DATE,
		"PES_REQUESTOR" CHAR(60),
		"PES_DATE_RESPONDED" DATE,
		"PES_STATUS_DETAILS" VARCHAR(200),
		"PES_STATUS" CHAR(50),
		"REVALIDATION_DATE_FIELD" DATE,
		"REVALIDATION_STATUS" CHAR(30),
		"CBN_DATE_FIELD" DATE,
		"CBN_STATUS" CHAR(10),
		"WORK_STREAM" CHAR(150),
		"CT_ID_REQUIRED" CHAR(3),
		"CT_ID" CHAR(10),
		"CIO_ALIGNMENT" CHAR(30),
		"PRE_BOARDED" CHAR(9),
		"SECURITY_EDUCATION" CHAR(3) NOT NULL DEFAULT 'No',
		"RF_FLAG" char(1) NOT NULL DEFAULT '0' constraint RF_BOOLH check ("RF_FLAG" in ('0','1'))
		"RF_START" DATE,
		"RF_END" DATE
	)
	DATA CAPTURE NONE;

ALTER TABLE "VBAC_UT"."PERSON" ADD CONSTRAINT "SQL171213120532360" PRIMARY KEY
	("CNUM");


DROP TABLE "VBAC_UT"."DELEGATE";

CREATE TABLE "VBAC_UT"."DELEGATE" (
		"CNUM" CHAR(9) NOT NULL,
		"EMAIL_ADDRESS" CHAR(60) NOT NULL,
		"DELEGATE_CNUM" CHAR(9) NOT NULL,
		"DELEGATE_EMAIL" CHAR(60) NOT NULL
		);

		
ALTER TABLE "ROB_DEV"."PERSON" DROP VERSIONING; 
		
ALTER TABLE "ROB_DEV"."PERSON"
  drop COLUMN "RING_FENCED";
  
  
  CHAR(3) NOT NULL DEFAULT 'No';		
  
  alter table ROB_DEV.PERSON DROP VERSIONING;

ALTER TABLE "ROB_DEV"."PERSON_HISTORY"
  drop COLUMN "RING_FENCED";

ALTER TABLE "ROB_DEV"."PERSON_HISTORY"
  add COLUMN "RF_FLAG" char(1) NOT NULL DEFAULT '0' constraint RF_BOOLH check ("RF_FLAG" in ('0','1'));
  

alter table ROB_DEV.PERSON ADD VERSIONING USE HISTORY TABLE ROB_DEV.PERSON_HISTORY;  
  
  
  ALTER TABLE "ROB_DEV"."PERSON_HISTORY"
  add COLUMN "RF_Start" date
  add column "RF_End" date;
  

  
  
alter table VBAC_UT.PERSON DROP VERSIONING;


ALTER TABLE "VBAC_UT"."PERSON"
  drop COLUMN "RF_Start"
  drop COLUMN "RF_End";


ALTER TABLE "VBAC_UT"."PERSON_HISTORY"
  drop COLUMN "RF_Start"
  drop COLUMN "RF_End";


ALTER TABLE "VBAC_UT"."PERSON"
  add COLUMN "RF_START" date
  add column "RF_END" date;

ALTER TABLE "VBAC_UT"."PERSON_HISTORY"
  add COLUMN "RF_START" date
  add column "RF_END" date;
  
CALL SYSPROC.ADMIN_CMD ('REORG TABLE VBAC_UT.PERSON');
CALL SYSPROC.ADMIN_CMD ('REORG TABLE VBAC_UT.PERSON_HISTORY');
  

alter table VBAC_UT.PERSON ADD VERSIONING USE HISTORY TABLE VBAC_UT.PERSON_HISTORY;  
  
  