--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "VBAC"."PERSON" (
		"CNUM" CHAR(9) NOT NULL,
		"OPEN_SEAT_NUMBER" CHAR(12),
		"FIRST_NAME" CHAR(30),
		"LAST_NAME" CHAR(40),
		"EMAIL_ADDRESS" CHAR(60),
		"NOTES_ID" CHAR(60),
		"LBG_EMAIL" CHAR(60),
		"EMPLOYEE_TYPE" CHAR(20),
		"FM_CNUM" CHAR(9),
		"FM_MANAGER_FLAG" CHAR(3),
		"CTB_RTB" CHAR(10),
		"TT_BAU" CHAR(3),
		"LOB" CHAR(40),
		"ROLE_ON_THE_ACCOUNT" VARCHAR(120),
		"ROLE_TECHNOLOGY" CHAR(40),
		"START_DATE" DATE,
		"PROJECTED_END_DATE" DATE,
		"COUNTRY" CHAR(40),
		"IBM_BASE_LOCATION" VARCHAR(512),
		"LBG_LOCATION" VARCHAR(512),
		"OFFBOARDED_DATE" DATE,
		"PES_DATE_REQUESTED" DATE,
		"PES_REQUESTOR" CHAR(60),
		"PES_DATE_RESPONDED" DATE,
		"PES_STATUS_DETAILS" VARCHAR(200),
		"PES_STATUS" CHAR(50),
		"REVALIDATION_DATE_FIELD" DATE,
		"REVALIDATION_STATUS" CHAR(30),
		"CBN_DATE_FIELD" DATE,
		"CBN_STATUS" CHAR(10),
		"WORK_STREAM" CHAR(150),
		"CONTRACTOR_ID_REQUIRED" CHAR(3),
		"CONTRACTOR_ID" CHAR(10),
		"CIO_ALIGNMENT" CHAR(30),
		"PRE_BOARDED" CHAR(9)
	)
	DATA CAPTURE NONE;

ALTER TABLE "VBAC"."PERSON" ADD CONSTRAINT "SQL171213120532360" PRIMARY KEY
	("CNUM");

