<?php
namespace vbac\emails;

use itdq\BlueMail;
use itdq\Loader;
use vbac\allTables;
use vbac\interfaces\notificationEmail;
use vbac\personRecord;

class pesTeamOfLeaversEmail implements notificationEmail {

    function send(personRecord $person, array $leavers = array()){

        $loader = new Loader();
        $now = new \DateTime();
        $pesEmail = null;          // Will be overridden when we include_once from emailBodies later.

        $pesTaskId = personRecord::getPesTaskId();

        $cnumPredicate = " CNUM IN ('" . implode("','",$leavers) . "') ";
        $allPesStatus = $loader->loadIndexed('PES_STATUS','CNUM',allTables::$PERSON,$cnumPredicate);
        $allNotesid = $loader->loadIndexed('NOTES_ID','CNUM',allTables::$PERSON,$cnumPredicate);
        $allRevalidation = $loader->loadIndexed('REVALIDATION_STATUS','CNUM',allTables::$PERSON,$cnumPredicate);

        include_once 'emailBodies/leaversForPes.php';
        $pesEmail.= "<h3>The following people have been identified as having left IBM</h3>";
        $pesEmail.= "<h4>Generated by vBac: " . $now->format('jS M Y') . "</h4>";
        $pesEmail.= "<table border='1' style='border-collapse:collapse;'  ><thead style='background-color: #cce6ff; padding:25px;'><tr><th style='padding:25px;'>CNUM</th><th style='padding:25px;'>Notes ID</th><th style='padding:25px;'>PES Status</th><th style='padding:25px;'>Revalidation Status</th></tr></thead><tbody>";

        foreach ($leavers as $serial) {
            $pesStatus = isset($allPesStatus[$serial]) ? $allPesStatus[$serial] : 'unknown';
            $notesId   = isset($allNotesid[$serial]) ? $allNotesid[$serial] : 'unknown';
            $revalidation   = isset($allRevalidation[$serial]) ? $allRevalidation[$serial] : 'unknown';
            $pesEmail.="<tr><td style='padding:15px;'>" . $serial . "</td><td style='padding:15px;'>" . $notesId  . "</td><td style='padding:15px;'>" . $pesStatus . "</td><td style='padding:15px;'>" . $revalidation . "</td></tr>";
        }

        $pesEmail.="</tbody></table>";
        $pesEmail.= "<style> th { background:red; padding:15px; } </style>";

        return BlueMail::send_mail(array($pesTaskId), "vBAC Leavers", $pesEmail, $pesTaskId);
    }
}