---
name: ci-build-and-deploy-production
on:
  push:
    branches:
      - prod
jobs:
  Build:
    runs-on:
      - aro-prod-westus3
    environment: production
    timeout-minutes: 60
    steps:
      - name: Get JFROG Credentials
        id: import-secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://vault.kyndryl.net
          method: token
          namespace: kyndryl/KYNDRYL_PRACTICES/
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: false
          secrets: |
            kps-gd-app-vbac/data/dev/w3us/jfrog JFROG_USER | JFROG_USER ; 
            kps-gd-app-vbac/data/dev/w3us/jfrog JFROG_TOKEN | JFROG_TOKEN
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Jfrog
        uses: docker/login-action@v2
        with:
          registry: kyndryl.jfrog.io
          username: ${{ steps.import-secrets.outputs.JFROG_USER }}
          password: ${{ steps.import-secrets.outputs.JFROG_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            ${{ vars.JFROG_URL }}/${{ vars.JFROG_CONTAINER }}/vbac:${{ vars.SHORT_NAME }}_${{ github.run_number }}
  Deploy:
    name: Deploy
    needs:
      - Build
    runs-on:
      - aro-prod-westus3
    environment: production
    timeout-minutes: 60
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v3
      - name: Import JFROG & ARO Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://vault.kyndryl.net
          method: token
          namespace: kyndryl/KYNDRYL_PRACTICES/
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: false
          secrets: |
            kps-gd-app-vbac/data/prod/w3us/jfrog JFROG_USER | JFROG_USER ;
            kps-gd-app-vbac/data/prod/w3us/jfrog JFROG_TOKEN | JFROG_TOKEN ;
            kps-gd-app-vbac/data/prod/w3us/openshift-sa SERVER_URL | SERVER_URL ;
            kps-gd-app-vbac/data/prod/w3us/openshift-sa SA_TOKEN | SA_TOKEN ;
            kps-gd-app-vbac/data/prod/w3us/openshift-sa NAMESPACE | NAMESPACE ;
            kps-gd-app-vbac/data/prod/w3us/sqlserver_wus3 server | DB_SERVER ;
            kps-gd-app-vbac/data/prod/w3us/sqlserver_wus3 database | DB_NAME ;
            kps-gd-app-vbac/data/prod/w3us/sqlserver_wus3 username | DB_USER_NAME ;
            kps-gd-app-vbac/data/prod/w3us/sqlserver_wus3 password | DB_USER_PW ;
            kps-gd-app-vbac/data/dev/w3us/smtpserver host | SMTP_HOST ;
            kps-gd-app-vbac/data/dev/w3us/smtpserver username | SMTP_USER_NAME ;
            kps-gd-app-vbac/data/dev/w3us/smtpserver password | SMTP_USER_PW ;
            kps-gd-app-vbac/data/prod/w3us/SSOserver host | SSO_HOST ;
            kps-gd-app-vbac/data/prod/w3us/SSOserver client_id | SSO_CLIENT_ID ;
            kps-gd-app-vbac/data/prod/w3us/SSOserver client_secret | SSO_CLIENT_SECRET ;
            kps-gd-app-vbac/data/prod/w3us/SSOserver client_api_token | SSO_API_TOKEN ;
            kps-gd-app-kpes/data/prod/w3us/Redis PORT | REDIS_PORT ;
            kps-gd-app-kpes/data/prod/w3us/Redis PASSWORD | REDIS_PW ;
            kps-gd-app-kpes/data/prod/w3us/cFIRST USER_ID | CFIRST_USER_ID ;
            kps-gd-app-kpes/data/prod/w3us/cFIRST PASSWORD | CFIRST_PW ;
            kps-gd-app-kpes/data/prod/w3us/cFIRST API_KEY | CFIRST_API_KEY
      - name: Get Worker API Credentials
        id: import-secrets-worker-api
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://vault.kyndryl.net
          method: token
          namespace: kyndryl/Non-CIO-Kyndryl/
          token: ${{ secrets.VAULT_TOKEN__WORKER_API }}
          tlsSkipVerify: false
          secrets: |
            kv-vbac-prod/data/azsp/apim AZURE_CLIENT_ID | CLIENT_ID ; 
            kv-vbac-prod/data/azsp/apim AZURE_CLIENT_SECRET | CLIENT_SECRET   
      - name: Login to ARO Cluster
        id: set-aro-context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ steps.import-secrets.outputs.SERVER_URL }}
          openshift_token: ${{ steps.import-secrets.outputs.SA_TOKEN }}
          insecure_skip_tls_verify: true
          namespace: ${{ steps.import-secrets.outputs.NAMESPACE }}