---
name: ci-build-and-deploy-production
on:
  push:
    branches:
      - prod
jobs:
  Build:
    runs-on:
      - aro-prod-westus3
    environment: production
    timeout-minutes: 60
    steps:
      - name: Get JFROG Credentials
        id: import-secrets
        uses: hashicorp/vault-action@v2.7.4
        with:
          url: https://vault.kyndryl.net
          method: token
          namespace: kyndryl/KYNDRYL_PRACTICES/
          token: ${{ secrets.VAULT_TOKEN }}
          tlsSkipVerify: false
          secrets: |
            kps-gd-app-vbac/data/dev/w3us/jfrog JFROG_USER | JFROG_USER ; 
            kps-gd-app-vbac/data/dev/w3us/jfrog JFROG_TOKEN | JFROG_TOKEN
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Jfrog
        uses: docker/login-action@v2
        with:
          registry: kyndryl.jfrog.io
          username: ${{ steps.import-secrets.outputs.JFROG_USER }}
          password: ${{ steps.import-secrets.outputs.JFROG_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | 
            ${{ vars.JFROG_URL }}/${{ vars.JFROG_CONTAINER }}/vbac:${{ vars.SHORT_NAME }}_${{ github.run_number }}
  Deploy:
    name: Deploy
    needs:
      - Build
    runs-on:
      - aro-prod-westus3
    environment: production
    timeout-minutes: 60
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v3